Voucherify Integration PoC
emporix/b2b-showcase pull request #4
Opened 2023-05-26 11:36 UTC by p-zielinski

Please see README-VOUCHERIFY.md for more details

2023-05-30 07:13 UTC, michalbujalski approved these changes

2023-06-07 20:38 UTC, lstypka requested changes

2023-06-07 20:38 UTC, lstypka commented on src/components/Cart/cart.js
> +  const discountsDetails = cart?.metadata?.mixins?.discountsDetails || []
Please change the line. to
```
  const discountsDetails = cart?.mixins?.voucherify?.discountsDetails || []
````

2023-06-07 20:38 UTC, lstypka commented on src/context/cart-provider.js
> +
please change the function to
```
  const mixins = useMemo(() => {
    return cartAccount?.mixins || {}
  }, [cartAccount?.mixins])
```

2023-06-07 20:38 UTC, lstypka commented on src/integration/buildIntegrationCartFromEmporixCart.js
> +  const currentlyAppliedCoupons = Array.isArray(
Please change the following four lines to:
```
    emporixCart?.mixins?.voucherify?.appliedCoupons
  )
    ? emporixCart?.mixins?.voucherify?.appliedCoupons
    : []
```

2023-06-07 20:38 UTC, lstypka commented on src/integration/buildIntegrationCartFromEmporixCart.js
> +    sessionKey: emporixCart.metadata?.mixins?.sessionKey,
please change the line to 
```
    sessionKey: emporixCart?.mixins?.voucherify?.sessionKey,
```

2023-06-07 20:38 UTC, lstypka commented on src/integration/emporix/emporixApi.js
> +export const updateCartMetadataMixins = async (
Please change the function according to this snippet
```
export const updateCartMetadataMixins = async (
  emporixCart,
  validationResult,
  deletedCodes,
  discountsDetails
) => {
  const { newSessionKey, applicableCoupons, availablePromotions } =
    validationResult
  const mixinsSchema = {
    ...(emporixCart?.metadata?.mixins || {})
  }
  mixinsSchema['voucherify'] = "https://res.cloudinary.com/saas-ag/raw/upload/v1686167929/voucherify/voucherify.json"
  
  const mixins = {
    ...(emporixCart?.mixins || {}),
    voucherify : {
      sessionKey: newSessionKey || emporixCart.mixins?.voucherify?.sessionKey,
      appliedCoupons: applicableCoupons
        .filter((coupon) => {
          if (!deletedCodes) {
            return true
          }
          return !deletedCodes.includes(coupon.id)
        })
        .map((coupon) => {
          return {
            code: coupon.id,
            status: 'APPLIED',
            type: coupon.object,
            banner: coupon.banner,
          }
        }),
      availablePromotions,
      discountsDetails,
    }
  }
  const emporixAccessToken = await getEmporixAPIAccessToken()
  const cartUpdate = await fetch(
    `${process.env.REACT_APP_API_URL}/cart/${localStorage.getItem(
      TENANT
    )}/carts/${emporixCart.id}`,
    {
      method: 'PUT',
      headers: {
        Authorization: `Bearer ${emporixAccessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
          mixins,
          metadata : {
            mixins : mixinsSchema
          }
      }),
    }
  )
  if (cartUpdate.status !== 204) {
    throw {
      error: `Could not update cart with id: ${emporixCart.id}`,
    }
  }
}
```

2023-06-07 20:38 UTC, lstypka commented on src/pages/cart/CartTable.js
> +  const discountsDetails = cart?.metadata?.mixins?.discountsDetails || []
please change the line to:
```
 const discountsDetails = cart?.mixins?.voucherify?.discountsDetails || []
```

2023-06-07 20:38 UTC, lstypka commented on src/pages/shared/Qualification.js
> +  const cartMixins = cartAccount.metadata?.mixins || {}
please change it to:
```
const cartMixins = cartAccount?.mixins?.voucherify || {}
 ```

2023-06-07 20:55 UTC, p-zielinski commented on src/integration/emporix/emporixApi.js
> +        metadata: {
Yes, I had to missed that :/
Thank You so much!

2023-06-15 15:33 UTC, lstypka approved these changes

2023-06-20 06:17 UTC, merged